#server:
#  port: 8082
#  servlet:
#    context-path: /api/v1

#org:
#  neo4j:
#    driver:
#      uri: bolt://localhost:7687
#      authentication:
#        username: neo4j
#        password: 123456

spring:
  neo4j:
    uri: bolt://0.0.0.0:7687
    authentication:
      username: neo4j
      password: 123456
  data:
    neo4j:
      database: neo4j

logging:
  level:
    org:
      apache:
        tomcat: DEBUG


compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024